/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出所有匯入批次 */
        get: operations["list_imports_api_imports_get"];
        put?: never;
        /**
         * 上傳結算單
         * @description 上傳並匯入一份結算單。
         *
         *     **同一份檔案重複上傳是安全的。** 服務端以檔案內容的 SHA-256 判斷，
         *     第二次上傳會回傳原批次且 `was_duplicate` 為真，不會重複入帳。
         */
        post: operations["create_import_api_imports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/imports/{batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看單一批次與它匯入的記錄 */
        get: operations["get_import_api_imports__batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出歷次對帳的 run_id */
        get: operations["list_reconciliations_api_reconciliations_get"];
        put?: never;
        /**
         * 執行一次對帳
         * @description 把資料庫裡的訂單與結算記錄跑一次三階段匹配。
         *
         *     回傳指標與 `run_id`；完整的四象限明細請用
         *     `GET /api/reconciliations/{run_id}/report`。
         */
        post: operations["create_reconciliation_api_reconciliations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reconciliations/{run_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查看四象限報告 */
        get: operations["get_report_api_reconciliations__run_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 列出我方訂單 */
        get: operations["list_orders_api_orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/platforms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 列出已支援的平台
         * @description 新增一個平台不需要修改這個端點——它讀的是 parser registry。
         */
        get: operations["list_platforms_api_platforms_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 健康檢查 */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BatchOut */
        BatchOut: {
            /** Batch Id */
            batch_id: string;
            /** Platform */
            platform: string;
            /** Filename */
            filename: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /** Row Count */
            row_count: number;
            /** Accepted Count */
            accepted_count: number;
            /** Rejected Count */
            rejected_count: number;
        };
        /** Body_create_import_api_imports_post */
        Body_create_import_api_imports_post: {
            /**
             * File
             * @description 平台匯出的結算單
             */
            file: string;
        };
        /**
         * CandidateOut
         * @description Stage 3 的候選。``reasons`` 是給人看的，不是給程式判斷的。
         */
        CandidateOut: {
            /** Order Id */
            order_id: string;
            /** External Order Id */
            external_order_id: string;
            /** Product Name */
            product_name: string;
            /** Score */
            score: string;
            /** Reasons */
            reasons: string[];
        };
        /**
         * ConfigOut
         * @description 對帳當下使用的設定。
         *
         *     報告一定要附上設定。「自動匹配率 79.6%」在門檻 0.5 與 0.9 下
         *     是完全不同的兩件事，沒有設定的數字沒有意義。
         */
        ConfigOut: {
            /** Accept Threshold */
            accept_threshold: string;
            amount_tolerance: components["schemas"]["MoneyOut"];
            /** Settlement Lag Days */
            settlement_lag_days: number[];
            /** Weight Amount */
            weight_amount: string;
            /** Weight Date */
            weight_date: string;
            /** Weight Product */
            weight_product: string;
        };
        /**
         * ErrorResponse
         * @description 統一的錯誤格式。
         *
         *     ``code`` 給程式判斷，``message`` 給人看。兩者分開，前端才不需要
         *     比對中文字串來決定行為。
         */
        ErrorResponse: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ImportResponse
         * @description 匯入結果。
         *
         *     ``was_duplicate`` 為真時代表這份檔案先前已經匯入過，
         *     本次沒有寫入任何資料——呼叫端必須能分辨這兩種「成功」。
         */
        ImportResponse: {
            /** Batch Id */
            batch_id: string;
            /** Platform */
            platform: string;
            /** Filename */
            filename: string;
            /**
             * Content Hash
             * @description 檔案內容的 SHA-256，冪等匯入的依據
             */
            content_hash: string;
            /**
             * Imported At
             * Format: date-time
             */
            imported_at: string;
            /** Row Count */
            row_count: number;
            /** Accepted Count */
            accepted_count: number;
            /** Rejected Count */
            rejected_count: number;
            /**
             * Skipped Duplicate Rows
             * @description 檔案指紋不同、但個別列先前已存在而被略過的筆數
             * @default 0
             */
            skipped_duplicate_rows: number;
            /**
             * Was Duplicate
             * @description 這份檔案先前是否已匯入過。為真時本次未寫入任何資料
             */
            was_duplicate: boolean;
            /** Message */
            message: string;
            /** Row Errors */
            row_errors?: components["schemas"]["RowErrorOut"][];
        };
        /** MatchResultOut */
        MatchResultOut: {
            /**
             * Outcome
             * @description 四象限之一：matched / amount_variance / missing_in_ledger / missing_in_settlement
             */
            outcome: string;
            /**
             * Stage
             * @description 1 精確、2 容差、3 模糊；未匹配時為 null
             */
            stage?: number | null;
            /**
             * Needs Review
             * @description 是否需要人工確認。只有 Stage 1 的 matched 為 false
             */
            needs_review: boolean;
            order?: components["schemas"]["OrderOut"] | null;
            /** Records */
            records: components["schemas"]["SettlementRecordOut"][];
            /** @description 平台實際撥款合計（多列時已抵銷退款） */
            settled_amount?: components["schemas"]["MoneyOut"] | null;
            variance?: components["schemas"]["MoneyOut"] | null;
            /** Variance Reason */
            variance_reason?: string | null;
            /** Candidates */
            candidates: components["schemas"]["CandidateOut"][];
        };
        /** MetricsOut */
        MetricsOut: {
            /** Order Count */
            order_count: number;
            /** Record Count */
            record_count: number;
            /** Duplicates Dropped */
            duplicates_dropped: number;
            /** Matched */
            matched: number;
            /** Amount Variance */
            amount_variance: number;
            /** Missing In Ledger */
            missing_in_ledger: number;
            /** Missing In Settlement */
            missing_in_settlement: number;
            /** Stage Exact */
            stage_exact: number;
            /** Stage Tolerant */
            stage_tolerant: number;
            /** Stage Fuzzy */
            stage_fuzzy: number;
            /**
             * Needs Review
             * @description 需人工確認的筆數。只有 Stage 1 的 matched 不需要
             */
            needs_review: number;
            /**
             * Automation Rate
             * @description 完全不需人工介入的比例。只計 Stage 1——那是唯一可以直接入帳的情況
             */
            automation_rate: number;
            /** Review Rate */
            review_rate: number;
            /** Elapsed Seconds */
            elapsed_seconds: number;
            /**
             * Candidate Comparisons
             * @description Stage 3 實際的候選比對次數。與 order_count × record_count 相比可看出索引的效果
             */
            candidate_comparisons: number;
        };
        /**
         * MoneyOut
         * @description 金額。
         *
         *     ``amount`` 是字串而不是數字，避免 JSON 的浮點數表示破壞精度。
         *     ``minor_units`` 一併回傳，讓需要精確計算的前端可以直接用整數。
         */
        MoneyOut: {
            /**
             * Amount
             * @description 以元為單位的十進位字串，例如 "944.70"
             */
            amount: string;
            /**
             * Currency
             * @description ISO 4217 幣別代碼
             * @example TWD
             */
            currency: string;
            /**
             * Minor Units
             * @description 最小貨幣單位的整數值，例如 94470
             */
            minor_units: number;
        };
        /** OrderOut */
        OrderOut: {
            /** Order Id */
            order_id: string;
            /** Platform */
            platform: string;
            /** External Order Id */
            external_order_id: string;
            /**
             * Ordered At
             * Format: date-time
             */
            ordered_at: string;
            /** Product Name */
            product_name: string;
            /** Quantity */
            quantity: number;
            gross_amount: components["schemas"]["MoneyOut"];
            expected_fee: components["schemas"]["MoneyOut"];
            expected_net: components["schemas"]["MoneyOut"];
        };
        /** PlatformOut */
        PlatformOut: {
            /** Code */
            code: string;
            /** Display Name */
            display_name: string;
        };
        /** ReconciliationRequest */
        ReconciliationRequest: {
            /**
             * Platform
             * @description 留空則對所有平台
             */
            platform?: string | null;
            /**
             * Accept Threshold
             * @description Stage 3 採納門檻，0 到 1 之間，例如 "0.82"
             */
            accept_threshold?: string | null;
        };
        /** ReconciliationResponse */
        ReconciliationResponse: {
            /** Run Id */
            run_id: string;
            metrics: components["schemas"]["MetricsOut"];
            config: components["schemas"]["ConfigOut"];
        };
        /** ReportResponse */
        ReportResponse: {
            /** Run Id */
            run_id: string;
            metrics: components["schemas"]["MetricsOut"];
            config: components["schemas"]["ConfigOut"];
            /** Results */
            results: components["schemas"]["MatchResultOut"][];
            /**
             * Total
             * @description 符合篩選條件的總筆數（未分頁前）
             */
            total: number;
        };
        /** RowErrorOut */
        RowErrorOut: {
            /** Row Number */
            row_number: number;
            /** Message */
            message: string;
        };
        /** SettlementRecordOut */
        SettlementRecordOut: {
            /** Platform */
            platform: string;
            /**
             * Settled At
             * Format: date
             */
            settled_at: string;
            /** External Order Id */
            external_order_id: string | null;
            /** Product Name */
            product_name: string | null;
            /** Source Row */
            source_row: number;
            /** Record Type */
            record_type: string;
            gross_amount: components["schemas"]["MoneyOut"];
            fee_amount: components["schemas"]["MoneyOut"];
            net_amount: components["schemas"]["MoneyOut"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_imports_api_imports_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchOut"][];
                };
            };
        };
    };
    create_import_api_imports_post: {
        parameters: {
            query?: {
                /** @description 留空則由內容自動偵測平台 */
                platform?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_import_api_imports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_import_api_imports__batch_id__get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                batch_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reconciliations_api_reconciliations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    create_reconciliation_api_reconciliations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReconciliationRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReconciliationResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_report_api_reconciliations__run_id__report_get: {
        parameters: {
            query?: {
                /** @description 依象限篩選：matched / amount_variance / missing_in_ledger / missing_in_settlement */
                outcome?: string | null;
                /** @description 只看需要人工確認的 */
                needs_review?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_orders_api_orders_get: {
        parameters: {
            query?: {
                platform?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrderOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_platforms_api_platforms_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlatformOut"][];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
