"""initial schema

Revision ID: d16d8b340007
Revises: 
Create Date: 2026-09-12 11:55:09.850615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16d8b340007'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=256), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('accepted_count', sa.Integer(), nullable=False),
    sa.Column('rejected_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_batches_batch_id'), ['batch_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_import_batches_content_hash'), ['content_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_import_batches_platform'), ['platform'], unique=False)

    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_order_id', sa.String(length=128), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('expected_fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_external_order_id'), ['external_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_orders_platform'), ['platform'], unique=False)
        batch_op.create_index('ix_orders_platform_external', ['platform', 'external_order_id'], unique=False)

    op.create_table('reconciliation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=False),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reconciliation_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reconciliation_runs_run_id'), ['run_id'], unique=True)

    op.create_table('match_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_pk', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('record_ids_json', sa.Text(), nullable=False),
    sa.Column('variance_minor', sa.BigInteger(), nullable=True),
    sa.Column('variance_reason', sa.String(length=32), nullable=True),
    sa.Column('candidates_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['run_pk'], ['reconciliation_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_pk', 'id', name='uq_match_result_run')
    )
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_results_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_results_outcome'), ['outcome'], unique=False)
        batch_op.create_index('ix_match_results_run_outcome', ['run_pk', 'outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_results_run_pk'), ['run_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_results_stage'), ['stage'], unique=False)

    op.create_table('settlement_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_pk', sa.Integer(), nullable=False),
    sa.Column('row_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_order_id', sa.String(length=128), nullable=True),
    sa.Column('settled_at', sa.DateTime().with_variant(sa.DateTime(), 'sqlite'), nullable=False),
    sa.Column('gross_minor', sa.BigInteger(), nullable=False),
    sa.Column('fee_minor', sa.BigInteger(), nullable=False),
    sa.Column('net_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('record_type', sa.String(length=16), nullable=False),
    sa.Column('product_name', sa.String(length=256), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('raw_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['batch_pk'], ['import_batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('settlement_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_settlement_records_batch_pk'), ['batch_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_records_external_order_id'), ['external_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_records_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_settlement_records_row_fingerprint'), ['row_fingerprint'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('settlement_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_settlement_records_row_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_settlement_records_platform'))
        batch_op.drop_index(batch_op.f('ix_settlement_records_external_order_id'))
        batch_op.drop_index(batch_op.f('ix_settlement_records_batch_pk'))

    op.drop_table('settlement_records')
    with op.batch_alter_table('match_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_results_stage'))
        batch_op.drop_index(batch_op.f('ix_match_results_run_pk'))
        batch_op.drop_index('ix_match_results_run_outcome')
        batch_op.drop_index(batch_op.f('ix_match_results_outcome'))
        batch_op.drop_index(batch_op.f('ix_match_results_order_id'))

    op.drop_table('match_results')
    with op.batch_alter_table('reconciliation_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reconciliation_runs_run_id'))

    op.drop_table('reconciliation_runs')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('ix_orders_platform_external')
        batch_op.drop_index(batch_op.f('ix_orders_platform'))
        batch_op.drop_index(batch_op.f('ix_orders_order_id'))
        batch_op.drop_index(batch_op.f('ix_orders_external_order_id'))

    op.drop_table('orders')
    with op.batch_alter_table('import_batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_batches_platform'))
        batch_op.drop_index(batch_op.f('ix_import_batches_content_hash'))
        batch_op.drop_index(batch_op.f('ix_import_batches_batch_id'))

    op.drop_table('import_batches')
    # ### end Alembic commands ###
